---
- name: Configure Windows Network Settings
  hosts: windows
  
  tasks:
    - name: Set Static IP Address
      ansible.windows.win_net_adapter:
        name: "Ethernet"
        ip_address: "192.168.1.50"
        netmask: "255.255.255.0"
        gateway: "192.168.1.1"

    - name: Set DNS Servers
      ansible.windows.win_dns_client:
        adapter_names: "Ethernet"
        ipv4_addresses:
          - "8.8.8.8"
          - "8.8.4.4"
