---
- name: Change Windows Administrator Password via iLO
  hosts: localhost
  vars:
    ilo-user: ""
    ilo_passoword: ""
    ilo-ip-address: ""
  
  tasks:
    - name: Change Windows password using iLO Redfish
      community.general.redfish_command:
        category: "Systems"
        command: "ResetBiosPassword"
        baseuri: "https://ilo-ip-address"
        username: "ilo-user"
        password: "ilo-password"
        timeout: 30
